Update ci_cd.yml

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -16,7 +16,6 @@ env:
   DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
 
 jobs:
-  
   info:
     if: github.event.action != 'closed'
     name: (INF) Print INFORMATION
@@ -27,7 +26,6 @@ jobs:
           echo "From: ${{ github.event.pull_request.head.ref }}"
           echo "To  : ${{ github.base_ref }}"
 
-  
   tst_unit:
     if: github.event.action != 'closed'
     name: (TST) Unit tests
@@ -48,7 +46,6 @@ jobs:
           sleep 2
           echo "OK"
 
-  
   sec_sast:
     if: github.event.action != 'closed'
     name: (SEC) / SAST
@@ -79,7 +76,6 @@ jobs:
           sleep 2
           echo "OK"
 
-  
   mark_tests_passed:
     if: ${{ github.event.action != 'closed'
           && needs.tst_unit.result == 'success'
@@ -111,7 +107,6 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           labels: sec-passed
 
-  
   gates:
     if: github.event.action != 'closed'
     name: (ISC) / collect statuses
@@ -127,7 +122,6 @@ jobs:
           allowed-conclusions: success
           ref: ${{ github.event.pull_request.head.sha }}
 
-  
   version:
     if: github.event.action != 'closed'
     name: (VER) Version UP
@@ -179,7 +173,6 @@ jobs:
           git commit -m "chore: bump version to $(cat version.txt)" || echo "No changes"
           git push origin HEAD:'${{ github.event.pull_request.head.ref }}'
 
-  
   changelog:
     if: github.event.action != 'closed'
     name: (VER) Changelog UP
@@ -215,7 +208,6 @@ jobs:
           git commit -m "docs: update changelog for v$(cat version.txt)" || echo "No changes"
           git push origin HEAD:'${{ github.event.pull_request.head.ref }}'
 
-  
   build:
     if: github.event.action != 'closed'
     name: (BUILD) / build
@@ -252,7 +244,6 @@ jobs:
           push: true
           tags: ${{ steps.tag.outputs.full }}
 
-      
       - name: Update DockerHub description and README
         uses: peter-evans/dockerhub-description@v3
         with:
@@ -261,14 +252,12 @@ jobs:
           repository: ${{ vars.DOCKERHUB_REPO }}
           readme-filepath: ./README.md
 
-      
       - name: Label PR "dockerhub"
         uses: actions-ecosystem/action-add-labels@v1
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           labels: dockerhub
 
-  
   notify:
     if: github.event.action != 'closed'
     name: (TG) Notify final
@@ -289,30 +278,72 @@ jobs:
             "${{ github.event.number }}" \
             "${DOCKERHUB_REPO}"
 
-  
   deploy:
-    if: false
+    if: >
+      github.event.action != 'closed' &&
+      contains(toJson(github.event.pull_request.labels), 'PROD')
     name: Deploy / PROD
     runs-on: self-hosted
     needs: [ notify ]
     environment: prod
     steps:
       - uses: actions/checkout@v4
-      - name: Run container
-        run: |
-          VER=$(tr -d '\r\n[:space:]' < version.txt)
-          bash .github/scripts/deploy.sh "${{ vars.DOCKERHUB_REPO }}:v${VER}"
 
-  
+      
+        
+        
+
+      - name: Read version (cmd)
+        id: ver
+        shell: cmd
+        run: |
+          set /p VER=<version.txt
+          set VER=%VER: =%
+          echo val=%VER%>> %GITHUB_OUTPUT%
+          echo Version: %VER%
+
+      - name: Deploy to self-hosted (cmd)
+        shell: cmd
+        env:
+          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+          DOCKERHUB_TOKEN:   ${{ secrets.DOCKERHUB_TOKEN }}
+        run: |
+          setlocal enabledelayedexpansion
+          set VER=${{ steps.ver.outputs.val }}
+          set IMAGE=${{ vars.DOCKERHUB_REPO }}:v!VER!
+          set NAME=land_devops
+          set PORTS=8080:80
+          echo Deploying !IMAGE! ...
+          docker login -u %DOCKERHUB_USERNAME% -p %DOCKERHUB_TOKEN% || echo "docker login skipped/failed (repo may be public)"
+          docker pull !IMAGE!
+          for /f "delims=" %%i in ('docker ps -aq -f "name=!NAME!"') do docker rm -f %%i
+          docker run -d --restart unless-stopped --name !NAME! -p !PORTS! !IMAGE!
+
+          echo ---- CONTAINERS ----
+          docker ps --filter "name=!NAME!" --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"
+          endlocal
+
   release:
-    if: github.event.action == 'closed' && github.event.pull_request.merged == true
-    name: Deploy / create release
+    if: always()
+    name: (REL) Create GitHub Release
     runs-on: ubuntu-latest
+    needs: [ deploy ]
     steps:
       - uses: actions/checkout@v4
-      - name: Create tag & release
+      - name: Read version
+        id: ver
+        run: |
+          VER=$(tr -d '\r\n[:space:]' < version.txt)
+          echo "val=$VER" >> "$GITHUB_OUTPUT"
+          echo "Version: $VER"
+
+      - name: Create GitHub Release
         uses: softprops/action-gh-release@v2
         with:
-          tag_name: v$(cat version.txt)
-          name: Релиз v$(cat version.txt)
-          body_path: CHANGELOG.md
+           token: ${{ secrets.GITHUB_TOKEN }}
+           tag_name: v${{ steps.ver.outputs.val }}
+           name: "Release v${{ steps.ver.outputs.val }}"
+           body_path: CHANGELOG.md
+           draft: false
+           prerelease: false
+           
